version: '2'
services:

  dev:
    build:
      context: ./
    image: muccg/ssh:${GIT_BRANCH}

  prod:
    build:
      context: ./
    image: muccg/ssh:${GIT_TAG}

  latest:
    extends:
      file: docker-compose-build.yml
      service: prod
    image: muccg/ssh:latest
